### ISSUE TITLE
Import container is too large on smaller screen

### ISSUE THREAD

**Issue by Vogeltak** [Dacaspex/Exhibit#100]
The import container is too large, causing the need of a scrollbar on the whole page. In such cases, it also becomes clear that the margin below the import button is insufficient to accommodate for pleasant viewing.

The height of the import container should be reduced on smaller screens (e.g. iPhone 5/SE).

See images below that illustrate the problem.

![image](https://user-images.githubusercontent.com/7063067/57776043-d0f5ba80-771e-11e9-8d2c-651bd4eb1c62.png)
![image](https://user-images.githubusercontent.com/7063067/57776397-aa844f00-771f-11e9-8ed6-933c79fcbc4a.png)

**Comment by Chessnl** [comment]
I believe this problem is also relevant for desktop. As there is a jump in sizes when the import screen adds a scrollbar whereas the previous screen did not. See images below. 

![image](https://user-images.githubusercontent.com/34745596/57841972-e117a380-77cb-11e9-9935-6c4b6a610763.png)
![image](https://user-images.githubusercontent.com/34745596/57841859-a3b31600-77cb-11e9-8b3a-a2c609140591.png)

The images are not very clear so its better to see yourself. Go to the initial screen, scale it until it has no scrollbar but the import screen does and switch between them.
