### ISSUE TITLE
[6] Table mockup

### ISSUE THREAD

**Issue by Dacaspex** [Dacaspex/Exhibit#124]
Estimated: 13

**Comment by Erik9519** [comment]
A possible way of displaying relative distances to POI and other information related to it could be to have, when at most 2 panels are open (For example settings + table), the table take 2/3 of the width of the screen and in 1/3 have the regular table whilst in the other 1/3 a table that relates the sheets to the selected POI's.

**Comment by cwognum** [comment]
Reviewed; Two suggestions
- Split up the columns of the tables some more.
- Add something to easily compare models.

### Some suggestions
**Switch to vertical design on small screens:** Perhaps something like [this](http://css.world/wp-content/uploads/2016/09/img-tablex-980x640.gif) might work nicely? Where on smaller screens not all columns are visible next to each other, but it becomes more of a vertical design? Or slight variations;
- Perhaps each row can be expanded and collapsed to show the data for that row? 
- Perhaps the the columns are listed on the left and the rows on the top on mobile devices? Like [this](https://www.webadvanced.com/Assets/Images/news/responsive_tables/octa-responsive-tables.gif)?

**Divide the columns over multiple tables:** Perhaps the data can be further split (for example in; The data you can always see and the data you can only see when you select a POI and a sheet). The other table can be shown in a new separate panel or perhaps be added to the graph panel. 

**Add a separate UI component for comparing sheets in different models:** I feel like it otherwise becomes a bit hard to keep it clear what the differences are. 

**Make the comparing more visually attractive:** I would use some graphic that quickly shows the differences between the sheets rather than just text. Perhaps something like this? 
![image](https://user-images.githubusercontent.com/28000055/58013514-058abd00-7af7-11e9-873f-5d71c49c8058.png)

**Comment by Chessnl** [comment]
Approved the following has been:

For each paper sheet currently in the system:
(Column order, Header name, Dropdown name, Tooltip name)
0, ID, -, -
1, Time, Time, Time in seconds since entering system
2, Pos., Position, Position on the path 
3, Vel., Velocity, Velocity in mm/s
4, Acc., Acceleration, Acceleration in mm/s^2
5, Prev. PoI, Previous PoI, Previous point of interest
6, Dis. prev. PoI, Distance to prev. PoI, Distance to previous PoI
7, Dis. prev. Sheet, Distance to prev. Sheet, Distance to previous Sheet
8, Dis. next Sheet, Distance to next Sheet, Distance to next Sheet

Additionally for each selected PoI i in {1, 2, 3 ... n} 
8 + i, Time at {PoI_i.name.trim}, Time at selected PoIs, Time since start simulation in seconds when at {PoI_i.name}
8 + n + i, Time from {PoI_i.name.trim}, Time from selected PoIs, Time since entering system in seconds when at {PoI_i.name} 
8 + 2n + i, Pos. from {PoI_i.name.trim}, Position from selected PoIs, Position on the path relative to {PoI_i.name}
8 + 3n + i, Vel. at {PoI_i.name.trim}, Velocity at selected PoIs, Velocity in mm/s when at {PoI_i.name}
8 + 4n + i, Acc. at {PoI_i.name.trim}, Acceleration at selected PoIs, Acceleration in mm/s^2 when at {PoI_i.name}

Entries in the ID column are {sheet.ID} if 1 timing file is selected.
Entries in the ID column are {sheet.ID},{timing.ID} if more than 1 timing files are selected

When a sheet is selected, an additional entry is added on top of the table. All those additionally added rows are sorted and placed on top of all other rows. Furthermore, all sheets already in the table will be marked/coloured as to indicate that they have been selected.

When a PoI is selected, and 2 timing models are loaded in, a difference is taken between the Vel. at {PoI_i.name.trim} / Acc. at {PoI_i.name.trim} for the different timing files (for each sheet).

{PoI_i.name.trim} regards the name of the PoI that is reduced in size (trimmed). When hovered over with the mouse, the full name will be displayed.

Optionally, the columns can be sorted on value.

**Comment by SquarePlayn** [comment]
Additionally:

- The table scrolls when it becomes too wide/high
- Columns can be turned on and off using a dropdown menu at the top
- For turning on columns that regard selected POIs, there will be only one of the above columns listed in the dropdown per property (so when 5 POIs are selected, only 1 option "Time at selected POIs" is in the dropdown). This will then enable that property column for all selected POIs at once.
- When multiple timing files are imported, the rows for timing file 1, timing file 2 and their relative difference can be turned on and/or off with a row configuration dropdown at the top left
- When there is only 1 timing file imported, the row selector dropdown is disabled (not clickable) and the row for timing file 1 (the only one) will be enabled.
- Optional extension: When scrolling down the header stays on screen
- Optional extension: When switching to mobile view, the columns are instead shown on the left with the sheets on the horizontal axis
- Optional extension: Columns are sortable
