### ISSUE TITLE
[20] Template

### ISSUE THREAD

**Issue by nolmoonen** [Dacaspex/Exhibit#17]
Estimate: 2

**Comment by Vogeltak** [comment]
- [x] Titlepage
- [x] Abstract
- [x] Table of contents
- [x] Document status sheet
- [x] Document change records since previous issue
- [x] 1.1 Purpose
- [x] 1.2 Scope
- [x] 1.3-1.4 List of definitions and abbreviations
- [x] 1.5 List of references
- [x] 1.6 Overview
- [x] 2 System overview
- [x] 3 System context
- [x] 4.1 Design method
- [x] 4.2 Decomposition description
- [x] 5 Component descriptions
- [x] 6 Feasibility and resource estimates
- [x] Requirements traceability matrix
- [x] Signing page

Template it complete. Contains all sections required by the course.
