### ISSUE TITLE
[5] Graph mockup

### ISSUE THREAD

**Issue by ArtixOfVenion** [Dacaspex/Exhibit#186]
Estimated: 13h

**Comment by cwognum** [comment]
Designing a mock-up is redundant. During the planning session, we drew some simple _mockups_ already. Designing these in software like Adobe XD costs more time than it is worth. We initially thought more data was needed, which would make the mockup useful, but this turns out to be a wrong estimate. 

The conclusions from the planning session can be found in #185 

![image](https://user-images.githubusercontent.com/28000055/58168214-00ac4180-7c8e-11e9-85e2-ee700bd45471.png)
