### ISSUE TITLE
[1] Mobile

### ISSUE THREAD

**Issue by nolmoonen** [Dacaspex/Exhibit#34]
Estimate: 5

**Comment by nolmoonen** [comment]
I am missing some elements, specified in the requirements:
* A field to view the current speed and time of the simulation.
* The Océ logo.

Also, I have some suggestions:
* Leave out the panel titles "viewport", "table", "graph", "configuration", since this takes up screen space and adds not much value.
* Rearrange the top buttons so the order is the same on mobile and desktop.

And can you clear the following up to me:
* How does the full screen work? Does it remain in portrait mode or does it go to landscape mode? (or can you have both?)
* How does the GUI work in landscape mode? Does the screen just not rotate, or does it go to desktop view?

**Comment by ArtixOfVenion** [comment]
[https://xd.adobe.com/view/ff0c8fb8-e16c-4986-5bcb-fb373b04eef7-893d/?fullscreen&hints=off](Updated version).
- Added missing elements
- For now I left in the titles, since this version will be used by customers as well, so titles such as "configuration" might result in better usability.
- Rearranged the top buttons to increase consistency.
-For the questions:
The fullscreen mode would function the same as in for example youtube's fullscreen mode, so once the button is pressed the phone will switch to landscape mode, putting the viewport in fullscreen.
For the GUI, I will create a simple landscape version to illustrate my vision. Will update this thread later in order to show this.

**Comment by ArtixOfVenion** [comment]
[Current version Work in progress](https://xd.adobe.com/view/562aeb16-ab2b-4478-75b5-e65572b06b51-201b/)
- Layout severely altered
- Color scheme edited to be more fitting with Océ colors
- Currently creating consistency between Desktop and mobile versions
